specVersion: 3
overrides:
- component:
    name: collector-cmd-builder
  newVersion: v0.117.0
  forceVersion: true
  files:
  - path: usr/bin/otelcol-contrib
- component:
    name: azure-sdk-for-go-sdk-azcore
  newVersion: v1.7.0
  forceVersion: true
  files:
  - path: usr/bin/otelcol-contrib
- component:
    name: golang-genproto
  newVersion: v0.0.0-20200911024640-645f7a48b24f
  forceVersion: true
  files:
  - path: usr/bin/otelcol-contrib
- component:
    name: mitchellh-mapstructure
  newVersion: v1.5.0
  forceVersion: true
  files:
  - path: usr/bin/otelcol-contrib
  vulnerabilityTriages:
- component:
    name: x-net
  triages:
  - cve: CVE-2025-22870
    resolution: FalsePositive
    comment: "x-net component is not using httpproxy"
