specVersion: 3
vulnerabilityTriages:
- component:
    name: glibc
  triages:
  - cve: CVE-2020-6096
    resolution: FalsePositive
    comment: '"Only applicable on ARMv7 targets."'
  - cve: CVE-2020-1751
    resolution: FalsePositive
    comment: '"Only applicable on PowerPC targets."'
  - cve: CVE-2019-6488
    resolution: FalsePositive
    comment: '"Only applicable on x32 targets."'
  - cve: CVE-2018-20796
    resolution: FalsePositive
    comment: '"Marked by upstream/Ubuntu/Red Hat as not a security bug, no fix available

      Rationale: Exploit requires crafted pattern in regex compiler meant only for
      trusted content"'
  - cve: CVE-2023-4911
    resolution: Patched
    comment: ''
  - cve: CVE-2023-5156
    resolution: Patched
    comment: ''
  - cve: CVE-2023-6246
    resolution: Patched
    comment: ''
  - cve: CVE-2023-6779
    resolution: Patched
    comment: ''
  - cve: CVE-2023-6780
    resolution: Patched
    comment: ''
