specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20240401170217-c3f982113cda
  forceVersion: 'true'
  files:
  - path: usr/bin/telegraf
- component:
    name: zap
  newVersion: v1.24.0
  forceVersion: 'true'
  files:
  - path: usr/bin/telegraf
vulnerabilityTriages:
- component:
    name: telegraf
  triages:
  - cve: CVE-2024-37298
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45337
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45338
    resolution: Patched
    comment: ''
