specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20250313205543-e70fdf4c4cb4
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
- component:
    name: github.com/open-edge-platform/edge-node-agents/cluster-agent
  newVersion: v1.6.1
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
- component:
    name: x-crypto
  newVersion: v0.43.0
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
- component:
    name: klauspost-compress
  newVersion: v1.18.0
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
- component:
    name: open-edge-platform-edge-node-agents-cluster-agent
  newVersion: 1.7.3
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
vulnerabilityTriages:
- component:
    name: cluster-agent
  triages:
  - cve: CVE-2024-45338
    resolution: FalsePositive
    comment: '"Package x-net already at the patched version 0.33.0. Lack of CPE data
      in NVD database.


      https://github.com/advisories/GHSA-w32m-9786-jp63"'
- component:
    name: protobuf
  triages:
  - cve: CVE-2019-15544
    resolution: FalsePositive
    comment: "This CVE is linked to a Rust component, but this specific component doesn't use Rust, making it invalid."
