specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20250313205543-e70fdf4c4cb4
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
- component:
    name: github.com/open-edge-platform/edge-node-agents/cluster-agent
  newVersion: v1.6.1
  forceVersion: true
  files:
  - path: usr/bin/cluster-agent
vulnerabilityTriages:
- component:
    name: cluster-agent
  triages:
  - cve: CVE-2024-45338
    resolution: FalsePositive
    comment: '"Package x-net already at the patched version 0.33.0. Lack of CPE data
      in NVD database.


      https://github.com/advisories/GHSA-w32m-9786-jp63"'
