specVersion: 3
overrides:
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/containerd
- component:
    name: moby
  newVersion: v23.0.3+incompatible
  forceVersion: true
  files:
  - path: usr/bin/containerd
  - path: usr/bin/containerd-stress
  - path: usr/bin/ctr
- component:
    name: x-crypto
  newVersion: v0.11.0
  forceVersion: true
  files:
  - path: usr/bin/containerd-stress
  - path: usr/bin/ctr
vulnerabilityTriages:
- component:
    name: moby-containerd-cc
  triages:
  - cve: CVE-2023-47108
    resolution: Patched
    comment: ''
  - cve: CVE-2023-44487
    resolution: Patched
    comment: ''
  - cve: CVE-2024-24786
    resolution: Patched
    comment: ''
  - cve: CVE-2024-28180
    resolution: Patched
    comment: ''
  - cve: CVE-2023-45288
    resolution: Patched
    comment: ''
