specVersion: 3
overrides:
- component:
    name: protobuf-java
  newVersion: v0.25.5
  forceVersion: true
  files:
  - path: usr/bin/bazel-real
  - path: A-server.jar
- component:
    name: perfmark-api
  newVersion: v0.19.0
  forceVersion: true
  files:
  - path: usr/bin/bazel-real
  - path: A-server.jar
- component:
    name: boringssl
  newVersion: v2.0.51
  forceVersion: true
  files:
  - path: META-INF/native/libnetty_tcnative_linux_x86_64.so
