specVersion: 3
overrides:
- component:
    name: azure-sdk-for-go-sdk-azcore
  newVersion: v1.16.0
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: azure-sdk-for-go-sdk-azidentity
  newVersion: v1.8.0
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: azure-sdk-for-go-sdk-internal
  newVersion: v1.10.0
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: azure-sdk-for-go-sdk-storage-azblob
  newVersion: v1.4.0
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: azure-sdk-for-go-sdk-storage-azdatalake
  newVersion: v1.2.0
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: azure-sdk-for-go-sdk-storage-azfile
  newVersion: v1.3.0
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: go-autorest-logger
  newVersion: v0.2.1
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: go-autorest-tracing
  newVersion: v0.6.0
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/azcopy
- component:
    name: Azure-azure-storage-azcopy
  newVersion: v10.25.1
  forceVersion: true
  files:
  - path: usr/bin/azcopy
vulnerabilityTriages:
- component:
    name: azcopy
  triages:
  - cve: CVE-2025-22868
    resolution: Patched
    comment: ''
