specVersion: 3
overrides:
- component:
    name: x-crypto
  newVersion: v0.44.0
  forceVersion: true
  files:
  - path: usr/bin/pm-agent
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/pm-agent
- component:
    name: golang-genproto
  newVersion: v0.0.0-20250825161204-c5933d9347a5
  forceVersion: true
  files:
  - path: usr/bin/pm-agent
- component:
    name: open-edge-platform-edge-node-agents-platform-manageability-agent
  newVersion: v0.3.1
  forceVersion: true
  files:
  - path: usr/bin/pm-agent