specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20250324211829-b45e905df463
  forceVersion: true
  files:
  - path: usr/bin/platform-update-agent
- component:
    name: github.com/open-edge-platform/edge-node-agents/platform-update-agent
  newVersion: v1.4.1
  forceVersion: true
  files:
  - path: usr/bin/platform-update-agent
- component:
    name: x-crypto
  newVersion: v0.38.0
  forceVersion: true
  files:
  - path: usr/bin/platform-update-agent
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/platform-update-agent
- component:
    name: kubernetes-klog
  newVersion: v2.130.1
  forceVersion: true
  files:
  - path: usr/bin/platform-update-agent
- component:
    name: open-edge-platform-edge-node-agents-platform-update-agent
  newVersion: 1.5.2
  forceVersion: true
  files:
  - path: usr/bin/platform-update-agent
vulnerabilityTriages:
- component:
    name: protobuf
  triages:
  - cve: CVE-2019-15544
    resolution: FalsePositive
    comment: "This CVE is linked to a Rust component, but this specific component doesn't use Rust, making it invalid."
