specVersion: 3
overrides:
- component:
    name: x-crypto
  newVersion: v0.36.0
  forceVersion: true
  files:
  - path: usr/bin/reporting-agent
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/reporting-agent
- component:
    name: mitchellh-mapstructure
  newVersion: v2.3.0
  forceVersion: true
  files:
  - path: usr/bin/reporting-agent
- component:
    name: open-edge-platform-edge-node-agents-reporting-agent
  newVersion: 0.0.4
  forceVersion: true
  files:
  - path: usr/bin/reporting-agent
vulnerabilityTriages:
- component:
    name: "x-crypto"
    version: "v0.36.0"
  files:
    - path: usr/bin/reporting-agent
  triages:
  - cve: CVE-2025-47913
    resolution: FalsePositive
    comment: "x-crypto component is not found as bundle software for reporting-agent/v0.1.0"
  - cve: CVE-2025-47914
    resolution: FalsePositive
    comment: "x-crypto component is not found as bundle software for reporting-agent/v0.1.0"
  - cve: CVE-2025-58181
    resolution: FalsePositive
    comment: "x-crypto component is not found as bundle software for reporting-agent/v0.1.0" 
