specVersion: 3
vulnerabilityTriages:
- component:
    name: tcl
  triages:
  - cve: CVE-2023-36328
    resolution: Patched
    comment: ''
  - cve: CVE-2023-45853
    resolution: Patched
    comment: ''
