specVersion: 3
overrides:
- component:
    name: code.cloudfoundry.org-cli
  newVersion: 8.7.3
  forceVersion: true
  files:
  - path: usr/bin/cf
vulnerabilityTriages:
- component:
    name: cf-cli
  triages:
  - cve: CVE-2024-45337
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45338
    resolution: Patched
    comment: ''
  - cve: CVE-2025-22869
    resolution: Patched
    comment: ''
