specVersion: 3
vulnerabilityTriages:
- component:
    name: snappy
  triages:
  - cve: CVE-2023-41330
    resolution: FalsePositive
    comment: '"it is reported to knplabs/knp-snappy, not https://github.com/google/snappy

      https://nvd.nist.gov/vuln/detail/CVE-2023-41330"'
