specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20240311173647-c811ad7063a7
  forceVersion: true
  files:
  - path: usr/bin/gh
- component:
    name: cli-cli
  newVersion: v2.62.0
  forceVersion: true
  files:
  - path: usr/bin/gh
