specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20240311173647-c811ad7063a7
  forceVersion: true
  files:
  - path: usr/bin/gh
- component:
    name: cli-cli
  newVersion: v2.62.0
  forceVersion: true
  files:
  - path: usr/bin/gh
vulnerabilityTriages:
- component:
    name: gh
  triages:
  - cve: CVE-2024-53858
    resolution: FalsePositive
    comment: ''
  - cve: CVE-2024-54132
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45337
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45338
    resolution: Patched
    comment: ''
  - cve: CVE-2024-53859
    resolution: Patched
    comment: ''
  - cve: CVE-2025-25204
    resolution: Patched
    comment: ''
  - cve: CVE-2025-27144
    resolution: Patched
    comment: ''
  - cve: CVE-2025-22869
    resolution: Patched
    comment: ''
