specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20250324211829-b45e905df463
  forceVersion: true
  files:
  - path: usr/bin/platform-telemetry-agent
- component:
    name: github.com/open-edge-platform/edge-node-agents/platform-telemetry-agent
  newVersion: v1.3.1
  forceVersion: true
  files:
  - path: usr/bin/platform-telemetry-agent
- component:
    name: x-crypto
  newVersion: v0.43.0
  forceVersion: true
  files:
  - path: usr/bin/platform-telemetry-agent
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/platform-telemetry-agent
- component:
    name: open-edge-platform-edge-node-agents-platform-telemetry-agent
  newVersion: 1.4.0
  forceVersion: true
  files:
  - path: usr/bin/platform-telemetry-agent
