specVersion: 3
overrides:
- component:
    name: golang-genproto
  newVersion: v0.0.0-20250324211829-b45e905df463
  forceVersion: true
  files:
  - path: usr/bin/node-agent
- component:
    name: github.com/open-edge-platform/edge-node-agents/node-agent
  newVersion: v1.6.2
  forceVersion: true
  files:
  - path: usr/bin/node-agent
- component:
    name: x-crypto
  newVersion: v0.36.0
  forceVersion: true
  files:
  - path: usr/bin/node-agent
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/node-agent
- component:
    name: klauspost-compress
  newVersion: v1.18.0
  forceVersion: true
  files:
  - path: usr/bin/node-agent
- component:
    name: zap
  newVersion: v1.18.1
  forceVersion: true
  files:
  - path: usr/bin/node-agent
vulnerabilityTriages:
- component:
    name: node-agent
  triages:
  - cve: CVE-2024-51744
    resolution: FalsePositive
    comment: '"Package golang-jwt already at the patched version 4.5.1. Lack of CPE
      data in NVD database.


      https://github.com/advisories/GHSA-29wx-vh33-7x7r"'
  - cve: CVE-2024-45338
    resolution: FalsePositive
    comment: '"Package x-net already at the patched version 0.33.0. Lack of CPE data
      in NVD database.


      https://github.com/advisories/GHSA-w32m-9786-jp63"'
