specVersion: 3
overrides:
- component:
    name: cni
  newVersion: v1.1.2
  forceVersion: true
  files:
  - path: usr/libexec/cni/sleep
  - path: usr/sbin/cnitool
vulnerabilityTriages:
- component:
    name: cni
  triages:
  - cve: CVE-2021-38561
    resolution: Patched
    comment: ''
  - cve: CVE-2022-32149
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45338
    resolution: Patched
    comment: ''
  - cve: CVE-2022-29526
    resolution: Patched
    comment: ''
