specVersion: 3
overrides:
- component:
    name: x-crypto
  newVersion: v0.31.0
  forceVersion: true
  files:
  - path: usr/bin/inb-provision-certs
vulnerabilityTriages:
- component:
    name: x-crypto
  triages:
  - cve: CVE-2025-22869
    resolution: FalsePositive
    comment: "x-crypto component is not using ssh/handshake"
