specVersion: 3
overrides:
- component:
    name: qt
  newVersion: 6.6.3
  forceVersion: true
  files:
  - path: usr/lib/libQt6Sql.so.6.6.3
vulnerabilityTriages:
- component:
    name: qtbase
  triages:
  - cve: CVE-2024-56732
    resolution: Patched
    comment: ''
