specVersion: 3
overrides:
- component:
    name: libiniparser
  newVersion: 4.1
  forceVersion: 'true'
  files:
  - path: 'usr/lib/libiniparser.so.1'
vulnerabilityTriages:
- component:
    name: iniparser
  triages:
  - cve: CVE-2025-0633
    resolution: Patched
    comment: ''
