specVersion: 3
overrides:
- component:
    name: lua
  newVersion: 5.4.6
  forceVersion: 'true'
  files:
  - path: 'usr/bin/sysbench'
vulnerabilityTriages:
- component:
    name: sysbench
  triages:
  - cve: CVE-2019-19391
    resolution: Patched
    comment: ''
