specVersion: 3
overrides:
- component:
    name: x-crypto
  newVersion: v0.36.0
  forceVersion: true
  files:
  - path: usr/bin/tink-worker
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/tink-worker
vulnerabilityTriages:
- component:
    name: moby
  triages:
  - cve: CVE-2025-54410
    resolution: FalsePositive
    comment: '"Containerd is used, not docker"'
- component:
    name: containerd
  triages:
  - cve: CVE-2024-40635
    resolution: FalsePositive
    comment: '"Package containerd already at the patched version 1.7.27."'
  - cve: CVE-2025-64329
    resolution: FalsePositive
    comment: '"tink-worker is using containerd client API not server"'
- component:
    name: x-net
  triages:
  - cve: CVE-2025-22872
    resolution: FalsePositive
    comment: '"x-net component is not using html/token"'
- component:
    name: protobuf
  triages:
  - cve: CVE-2019-15544
    resolution: FalsePositive
    comment: "This CVE is linked to a Rust component, but this specific component doesn't use Rust, making it invalid."
  - cve: CVE-2025-53605
    resolution: FalsePositive
    comment: "This CVE is linked to a Rust component, but this specific component doesn't use Rust, making it invalid."

