specVersion: 3
overrides:
- component:
    name: x-crypto
  newVersion: v0.36.0
  forceVersion: true
  files:
  - path: usr/bin/tink-worker
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/tink-worker
vulnerabilityTriages:
- component:
    name: containerd
  triages:
  - cve: CVE-2024-40635
    resolution: FalsePositive
    comment: '"Package containerd already at the patched version 1.7.27."'
- component:
    name: x-net
  triages:
  - cve: CVE-2025-22872
    resolution: FalsePositive
    comment: '"x-net component is not using html/token"'
