specVersion: 3
overrides:
- component:
    name: hiredis
  newVersion: v0.11.0
  forceVersion: 'true'
  files:
  - path: usr/bin/ntopng
- component:
    name: mongoose
  newVersion: v3.7
  forceVersion: 'true'
  files:
  - path: usr/bin/ntopng
- component:
    name: rrdtool
  newVersion: v1.4.8
  forceVersion: 'true'
  files:
  - path: usr/bin/ntopng
