specVersion: 3
overrides:
- component:
    name: go-autorest-autorest
  newVersion: v0.11.9
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: go-autorest-logger
  newVersion: v0.2.1
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: go-autorest-tracing
  newVersion: v0.6.0
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: go-radix
  newVersion: v0.0.0-20180808171621-7fddfc383310
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: gonum-blas
  newVersion: v0.11.0
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: gonum-lapack
  newVersion: v0.11.0
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: gonum-matrix
  newVersion: v0.11.0
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: google-cloud-go-longrunning
  newVersion: v0.82.0
  forceVersion: true
  files:
  - path: usr/bin/influxd
- component:
    name: klauspost-compress
  newVersion: v1.14.2
  forceVersion: true
  files:
  - path: usr/bin/telemetryd
- component:
    name: x-crypto
  newVersion: v0.14.0
  forceVersion: true
  files:
  - path: usr/bin/telemetryd
- component:
    name: xid
  newVersion: v1.2.1
  forceVersion: true
  files:
  - path: usr/bin/influxd
vulnerabilityTriages:
- component:
    name: influxdb
  triages:
  - cve: CVE-2021-4238
    resolution: Patched
    comment: ''
  - cve: CVE-2019-0205
    resolution: Patched
    comment: ''
  - cve: CVE-2024-6104
    resolution: Patched
    comment: ''
  - cve: CVE-2023-45288
    resolution: Patched
    comment: ''
  - cve: CVE-2024-24786
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45338
    resolution: Patched
    comment: ''
  - cve: CVE-2024-28180
    resolution: Patched
    comment: ''
  - cve: CVE-2025-27144
    resolution: Patched
    comment: ''
  - cve: CVE-2025-22868
    resolution: Patched
    comment: ''
