specVersion: 3
overrides:
- component:
    name: x-crypto
  newVersion: v0.43.0
  forceVersion: true
  files:
  - path: usr/bin/inb*
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/inb*
- component:
    name: golang-genproto
  newVersion: v0.0.0-20250804133106-a7a43d27e69b
  forceVersion: true
  files:
  - path: usr/bin/inb*