specVersion: 3
overrides:
- component:
    name: libdnet
  newVersion: v1.10
  forceVersion: 'true'
  files:
  - path: usr/bin/nmap
  - path: usr/bin/nping
- component:
    name: liblinear
  newVersion: v2.47
  forceVersion: 'true'
  files:
  - path: usr/bin/nmap
vulnerabilityTriages:
- component:
    name: nmap
  triages:
  - cve: CVE-2024-8006
    resolution: Patched
    comment: ''
  - cve: CVE-2023-7256
    resolution: Patched
    comment: ''
