specVersion: 3
vulnerabilityTriages:
- component:
    name: unzip
  triages:
  - cve: CVE-2008-0888
    resolution: FalsePositive
    comment: '"Upstream has fixed CVE-2008-0888 in 6.0"'
  - cve: CVE-2014-9636
    resolution: Patched
    comment: ''
  - cve: CVE-2015-1315
    resolution: Patched
    comment: ''
  - cve: CVE-2015-7696
    resolution: Patched
    comment: ''
  - cve: CVE-2016-9844
    resolution: Patched
    comment: ''
  - cve: CVE-2014-9913
    resolution: Patched
    comment: ''
  - cve: CVE-2018-18384
    resolution: Patched
    comment: ''
  - cve: CVE-2014-8139
    resolution: Patched
    comment: ''
  - cve: CVE-2014-8140
    resolution: Patched
    comment: ''
  - cve: CVE-2014-8141
    resolution: Patched
    comment: ''
  - cve: CVE-2019-13232
    resolution: Patched
    comment: ''
  - cve: CVE-2015-7697
    resolution: Patched
    comment: ''
  - cve: CVE-2018-1000035
    resolution: Patched
    comment: ''
  - cve: CVE-2022-0529
    resolution: Patched
    comment: ''
