specVersion: 3
overrides:
- component:
    name: aws-sdk-go
  newVersion: v1.17.6
  forceVersion: true
  files:
  - path: usr/bin/dockerd
- component:
    name: etcd
  newVersion: v3.3.10+incompatible
  forceVersion: true
  files:
  - path: usr/bin/dockerd
- component:
    name: fileutil
  newVersion: v0.5.0
  forceVersion: true
  files:
  - path: usr/bin/dockerd
- component:
    name: google-cloud-go-datastore
  newVersion: v1.0.0
  forceVersion: true
  files:
  - path: usr/bin/dockerd
- component:
    name: kubernetes-api
  newVersion: v0.17.4
  forceVersion: true
  files:
  - path: usr/bin/dockerd
- component:
    name: storage
  newVersion: v1.0.0
  forceVersion: true
  files:
  - path: usr/bin/dockerd
vulnerabilityTriages:
- component:
    name: moby-engine
  triages:
  - cve: CVE-2022-2879
    resolution: Patched
    comment: ''
  - cve: CVE-2024-41110
    resolution: Patched
    comment: ''
  - cve: CVE-2024-29018
    resolution: Patched
    comment: ''
  - cve: CVE-2024-24786
    resolution: Patched
    comment: ''
  - cve: CVE-2024-36621
    resolution: Patched
    comment: ''
  - cve: CVE-2024-36620
    resolution: Patched
    comment: ''
  - cve: CVE-2024-36623
    resolution: Patched
    comment: ''
  - cve: CVE-2024-45337
    resolution: Patched
    comment: ''
  - cve: CVE-2023-45288
    resolution: Patched
    comment: ''
