specVersion: 3
overrides:
- component:
    name: go-autorest-autorest
  newVersion: v0.11.19
  forceVersion: true
  files:
  - path: usr/bin/packer
- component:
    name: go-autorest-logger
  newVersion: v0.2.1
  forceVersion: true
  files:
  - path: usr/bin/packer
- component:
    name: go-autorest-tracing
  newVersion: v0.6.0
  forceVersion: true
  files:
  - path: usr/bin/packer
- component:
    name: go-yaml
  newVersion: v3.0.1
  forceVersion: true
  files:
  - path: usr/bin/packer
- component:
    name: google-cloud-go-datastore
  newVersion: v1.15.0
  forceVersion: true
  files:
  - path: usr/bin/packer
vulnerabilityTriages:
- component:
    name: packer
  triages:
  - cve: CVE-2025-21614
    resolution: FalsePositive
    comment: '"# fixed by CVE-2025-21613.patch file"'
  - cve: CVE-2022-3064
    resolution: Patched
    comment: ''
  - cve: CVE-2024-6104
    resolution: Patched
    comment: ''
  - cve: CVE-2024-24786
    resolution: Patched
    comment: ''
  - cve: CVE-2025-21613
    resolution: Patched
    comment: ''
  - cve: CVE-2024-28180
    resolution: Patched
    comment: ''
  - cve: CVE-2025-27144
    resolution: Patched
    comment: ''
  - cve: CVE-2025-22869
    resolution: Patched
    comment: ''
  - cve: CVE-2025-22868
    resolution: Patched
    comment: ''
