specVersion: 3
overrides:
- component:
    name: rancher-local-path-provisioner
  newVersion: v0.0.24
  forceVersion: true
  files:
  - path: usr/bin/local-path-provisioner
- component:
    name: grpc-go
  newVersion: v1.31.0
  forceVersion: true
  files:
  - path: usr/bin/local-path-provisioner
vulnerabilityTriages:
- component:
    name: local-path-provisioner
  triages:
  - cve: CVE-2023-45288
    resolution: Patched
    comment: ''
  - cve: CVE-2023-39325
    resolution: Patched
    comment: ''
  - cve: CVE-2023-44487
    resolution: Patched
    comment: ''
