specVersion: 3
vulnerabilityTriages:
- component:
    name: libtar
  triages:
  - cve: CVE-2021-33645
    resolution: FalsePositive
    comment: '"CVE-2021-33645 - Already addressed in SPECS/libtar/CVE-2021-33640.patch"'
  - cve: CVE-2021-33646
    resolution: FalsePositive
    comment: '"CVE-2021-33646 - Already addressed in SPECS/libtar/CVE-2021-33640.patch"'
