specVersion: 3
overrides:
- component:
    name: gtk+
  newVersion: 3.24.28
  forceVersion: 'true'
  files:
  - path: 'usr/lib/libgtk-3.so.0.2404.24'
- component:
    name: libxkbcommon
  newVersion: 1.6.0
  forceVersion: 'true'
  files:
  - path: 'usr/lib/libgdk-3.so.0.2404.24'
vulnerabilityTriages:
- component:
    name: gtk3
  triages:
  - cve: CVE-2024-6655
    resolution: Patched
    comment: ''
