#!/usr/bin/python

import os
import logging
import argparse

parser = argparse.ArgumentParser(description='Repository Synchronization Checker between edge-microvisor-repo and bdba-config-repo')
parser.add_argument('--edge-repo-path', required=True, type=str, default='edge-microvisor-repo', help='Path to the edge-microvisor-repo repository')
parser.add_argument('--bdba-repo-path', required=True, type=str, default='bdba-config-repo', help='Path to the bdba-config-repo repository')
args = parser.parse_args()

logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG, force=True)

logging.info(f"*"*100)
logging.info(f"\tStarting repository synchronization check...")
logging.info(f"*"*100)

if os.path.exists(args.edge_repo_path):
    specs = os.listdir(f"{args.edge_repo_path}/SPECS")
    logging.info(f"Found {len(specs)} packages in {args.edge_repo_path}/SPECS")

if os.path.exists(args.bdba_repo_path):
    cfgs = os.listdir(f"{args.bdba_repo_path}/SPECS")
    logging.info(f"Found {len(cfgs)} packages in {args.bdba_repo_path}/SPECS\n\n")

new_specs_dir = []
for specpkg in specs:
    if specpkg not in cfgs and specpkg != '.gitignore':
        # logging.warning(f"Package {specpkg} is required in bdba-config-repo/SPECS")
        new_specs_dir.append(specpkg)

logging.info(f"*"*100)
logging.info(f"\tTotal of {len(new_specs_dir)} SPECS/<package> are require to be adaded into bdba-config-repo/SPECS repository")
logging.info(f"*"*100)
logging.info(f"{new_specs_dir}\n\n")

obs_specs_dir = []
for cfgpkg in cfgs:
    if cfgpkg not in specs and cfgpkg not in new_specs_dir and cfgpkg != '.gitignore':
        # logging.info(f"Package {cfgpkg} is obsolete in bdba-config-repo/SPECS and can be removed")
        obs_specs_dir.append(cfgpkg)

logging.info(f"*"*100)
logging.info(f"\tTotal of {len(obs_specs_dir)} SPECS/<package> are require to be removed from bdba-config-repo/SPECS repository")
logging.info(f"*"*100)
logging.info(f"{obs_specs_dir}")

# Create new directories if they don't exist
if len(new_specs_dir) > 0:
    for pkg in new_specs_dir:
        os.makedirs(f'{args.bdba_repo_path}/SPECS/{pkg}', exist_ok=True)
        if os.path.exists(f"{args.bdba_repo_path}/SPECS/{pkg}"):
            with open(f"{args.bdba_repo_path}/SPECS/{pkg}/.bdba.yaml", 'w') as f:
                f.write('# Generated by automated bot to create initial Analysis Configuration File (.bdba.yaml)"\n---\nspecVersion: 3\n\n')
            f.close()
            logging.info(f"${pkg}/.bdba.yaml has been added to bdba-config-repo/SPECS/{pkg} repository")
else:
    logging.info(f"No new SPECS/<package> to be added into bdba-config-repo/SPECS repository")