specVersion: 3
overrides:
- component:
    name: k8s.io-node-problem-detector
  newVersion: v0.8.15
  forceVersion: 'true'
  files:
  - path: usr/bin/health-checker
  - path: usr/bin/log-counter
  - path: usr/bin/node-problem-detector
- component:
    name: x-crypto
  newVersion: v0.14.0
  forceVersion: 'true'
  files:
  - path: usr/bin/health-checker
  - path: usr/bin/log-counter
- component:
    name: kubernetes-client
  newVersion: v0.29.0
  forceVersion: 'true'
  files:
  - path: usr/bin/log-counter
- component:
    name: go-yaml
  newVersion: v2.4.0
  forceVersion: 'true'
  files:
  - path: usr/bin/node-problem-detector
vulnerabilityTriages:
- component:
    name: node-problem-detector
  triages:
  - cve: CVE-2024-45338
    resolution: Patched
    comment: ''
  - cve: CVE-2025-22868
    resolution: Patched
    comment: ''
  - cve: CVE-2025-22869
    resolution: Patched
    comment: ''
