specVersion: 3
overrides:
- component:
    name: acpica
  newVersion: 20190509
  forceVersion: 'true'
  files:
  - path: 'usr/bin/acpibin'
  - path: 'usr/bin/acpidump'
  - path: 'usr/bin/acpiexamples'
  - path: 'usr/bin/acpiexec'
  - path: 'usr/bin/acpihelp'
  - path: 'usr/bin/acpinames'
  - path: 'usr/bin/acpisrc'
  - path: 'usr/bin/acpixtract'
  - path: 'usr/bin/iasl'
vulnerabilityTriages:
- component:
    name: acpica-tools
  triages:
  - cve: CVE-2017-13693
    resolution: Patched
    comment: ''
  - cve: CVE-2017-13694
    resolution: Patched
    comment: ''
  - cve: CVE-2017-13695
    resolution: Patched
    comment: ''
