specVersion: 3
vulnerabilityTriages:
- component:
    name: qemu
  triages:
  - cve: CVE-2024-3567
    resolution: Patched
    comment: ''
  - cve: CVE-2023-6683
    resolution: Patched
    comment: ''
  - cve: CVE-2023-6693
    resolution: Patched
    comment: ''
