specVersion: 3
overrides:
- component:
    name: libbacktrace
  newVersion: 13.2.0-7.emt3
  forceVersion: true
  files:
  - path: usr/bin/gdb
vulnerabilityTriages:
- component:
    name: gdb
  triages:
  - cve: CVE-2023-39128
    resolution: Patched
    comment: ''
  - cve: CVE-2023-39129
    resolution: Patched
    comment: ''
  - cve: CVE-2023-39130
    resolution: Patched
    comment: ''
